import React from "react";
import "./ReportValueStack.css";
import { FileText, CheckCircle2, ShieldCheck, Gift, ArrowRight } from "lucide-react";

export default function ReportValueStack({ onNavigateCheckout }) {
  const items = [
    {
      title: "16-Directional Zone Energy Heatmap",
      desc: "Detailed visual mapping of your floor plan showing North, North-East, South-West, and 13 other energy zones with exact degree calculations.",
      val: "₹1,499 Value"
    },
    {
      title: "100% Non-Demolition Remedial Blueprint",
      desc: "Step-by-step easy fixes using color tapes, metallic strips, copper wires, and crystal placements. No wall breaking required.",
      val: "₹1,999 Value"
    },
    {
      title: "Room-by-Room Vastu Compliance Score",
      desc: "Individual energy ratings for your entrance, kitchen, master bedroom, toilets, and water storage with immediate corrective actions.",
      val: "₹999 Value"
    },
    {
      title: "Personal Astro-Vastu Gemstone & Chakra Alignment",
      desc: "Tailored planetary recommendations based on your birth date to remove obstacles in wealth, health, and relationship growth.",
      val: "₹1,499 Value"
    }
  ];

  return (
    <section className="py-14 px-4 md:px-8 bg-gradient-to-b from-[#fffbf7] via-[#fff5eb] to-[#fffbf7] relative">
      <div className="max-w-[1400px] mx-auto space-y-12">
        
        {/* Section Title */}
        <div className="text-center max-w-3xl mx-auto space-y-3">
          <span className="bg-[#ea580c]/10 text-[#ea580c] border border-orange-300 text-xs font-bold px-4 py-1.5 rounded-full uppercase tracking-wider">
            Unbeatable Value Stack
          </span>
          <h2 className="text-3xl md:text-5xl font-extrabold text-slate-900 font-sora">
            What You Receive In Your <span className="orange-gradient-text">24-Page Vastu Report</span>
          </h2>
          <p className="text-slate-600 text-base">
            Generated by Acharya Ji's Vastu Engine in minutes and delivered instantly to your WhatsApp & Email.
          </p>
        </div>

        {/* 2 Column Layout: Left 3D Book Graphic, Right Value Cards */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-center">
          
          {/* Left Generated 3D Book Visual */}
          <div className="lg:col-span-5 flex justify-center">
            <div className="white-orange-card p-6 rounded-3xl border-2 border-orange-200 shadow-2xl relative bg-white text-center max-w-md w-full">
              <img 
                src="/vastu-report-mockup.png" 
                alt="24-Page Vastu Report 3D Mockup" 
                className="w-full h-auto object-contain rounded-2xl shadow-md"
              />
              <div className="mt-4 space-y-1">
                <h4 className="text-lg font-extrabold text-slate-900 font-sora">Official 24-Page Vastu PDF</h4>
                <p className="text-xs text-[#ea580c] font-bold">100% Custom Tailored to Your Property</p>
              </div>
            </div>
          </div>

          {/* Right 4 Report Feature Cards */}
          <div className="lg:col-span-7 space-y-4">
            {items.map((item, idx) => (
              <div key={idx} className="white-orange-card white-orange-card-hover p-5 rounded-2xl flex items-start gap-4">
                <div className="p-3 bg-orange-50 text-[#f97316] rounded-xl border border-orange-200 shrink-0">
                  <FileText size={22} />
                </div>
                <div className="space-y-1 flex-1">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <h3 className="text-base font-bold text-slate-900">{item.title}</h3>
                    <span className="text-xs font-mono font-extrabold text-emerald-700 bg-emerald-100 px-2.5 py-0.5 rounded-full border border-emerald-300">
                      {item.val}
                    </span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed font-normal">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>

        </div>

        {/* Price Box Callout */}
        <div className="white-orange-card p-8 md:p-10 rounded-3xl border-2 border-orange-300 bg-white text-center max-w-2xl mx-auto space-y-6 shadow-2xl">
          <div className="inline-flex items-center gap-2 bg-amber-100 text-amber-900 text-xs font-bold px-4 py-1.5 rounded-full border border-amber-300">
            <Gift size={15} className="text-[#ea580c]" />
            <span>Bonus Offer Included Today</span>
          </div>

          <div className="space-y-1">
            <div className="text-xs text-slate-500 uppercase tracking-widest font-bold">Total Package Value: ₹5,996</div>
            <div className="text-3xl md:text-5xl font-extrabold text-slate-900 font-sora flex items-center justify-center gap-3">
              <span className="orange-gradient-text">Today Only: ₹999</span>
              <span className="text-slate-400 text-lg md:text-2xl line-through font-normal">₹5,999</span>
            </div>
            <p className="text-xs md:text-sm text-emerald-700 font-bold">
              🎉 You Save ₹5,000 Special Ads Discount
            </p>
          </div>

          <button 
            onClick={onNavigateCheckout}
            className="w-full sm:w-auto btn-orange-primary text-sm md:text-base px-10 py-4 flex items-center justify-center gap-2 mx-auto cursor-pointer font-extrabold"
          >
            <span>Get My Full 24-Page Vastu Report @ ₹999</span>
            <ArrowRight size={18} />
          </button>

          <div className="flex items-center justify-center gap-4 text-xs text-slate-500 font-medium">
            <span className="flex items-center gap-1"><ShieldCheck size={15} className="text-emerald-600" /> 100% Money-Back Guarantee</span>
            <span>•</span>
            <span>Instant PDF Download</span>
          </div>
        </div>

      </div>
    </section>
  );
}
